package leaves

const (
	testAnalyserPath           = "analyser.go"
	testHerculesMainPath       = "cmd/hercules/main.go"
	testTravisPath             = ".travis.yml"
	testBurndownPath           = "burndown.go"
	testPersonOneSource        = "one@srcd"
	testPersonTwoSource        = "two@srcd"
	testPersonOne              = "one"
	testPersonTwo              = "two"
	testPersonThree            = "three"
	testPersonFour             = "four"
	testPersonAlice            = "Alice"
	testPersonBob              = "Bob"
	testPersonCharlie          = "Charlie"
	testSourceDirectory        = "src"
	testDocsDirectory          = "docs"
	testMainPath               = "main.go"
	testReadmePath             = "README.md"
	testFileTestPath           = "file_test.go"
	testLicensePath            = "LICENSE2"
	testFileTwoPath            = "file2.go"
	testRBTreeTwoPath          = "rbtree2.go"
	testNumericPersonOneSource = "1@srcd"
	testAlphaPath              = "alpha.go"
	testBetaPath               = "beta.go"
	testGammaPath              = "gamma.go"
	testSysImport              = "sys"
	testPythonLanguage         = "Python"
	testFileOnePath            = "file1.go"
	testFileThreePath          = "file3.go"
	testFileFourPath           = "file4.go"
	testAuthorZero             = "author0"
	testDemoPath               = "demo.go"
)
