name: tests

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-lint:
    uses: ./.github/workflows/test-lint.yaml

  test-format:
    uses: ./.github/workflows/test-format.yaml

  test-dependency-review:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/test-dependency-review.yaml

  test-unit:
    uses: ./.github/workflows/test-unit.yaml

  test-deterministic:
    uses: ./.github/workflows/test-deterministic.yaml

  test-race:
    uses: ./.github/workflows/test-race.yaml

  test-fuzz:
    uses: ./.github/workflows/test-fuzz.yaml

  test-e2e:
    uses: ./.github/workflows/test-e2e.yaml

  test-visual:
    uses: ./.github/workflows/test-visual.yaml

  test-schema:
    uses: ./.github/workflows/test-schema.yaml

  test-vulnerability:
    uses: ./.github/workflows/test-vulnerability.yaml

  test-crosscompile:
    uses: ./.github/workflows/test-crosscompile.yaml

  test-build:
    uses: ./.github/workflows/test-build.yaml
